name: 'Develop Pull Request'
'on':
  pull_request:
    branches:
      - develop

jobs:
  # lint_and_prettier:
  #   uses: ./.github/workflows/lint_and_prettier.yml

  build:
    uses: ./.github/workflows/build_and_upload_artifact.yml

  # TODO: add test
  #test:
  #  needs: [lint_and_prettier, build]
  #  uses: ./.github/workflows/test.yml

  # deploy_and_preview:
  #   needs: [lint_and_prettier, build]
  #   if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         cache: yarn

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Download build artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: out
  #         path: out
