name: 'Develop Pull Request'
'on':
  pull_request:
    branches:
      - develop

jobs:
  lint_and_prettier:
    uses: ./.github/workflows/lint_and_prettier.yml

  build:
    uses: ./.github/workflows/build_and_upload_artifact.yml

  # TODO: add test
  #test:
  #  needs: [lint_and_prettier, build]
  #  uses: ./.github/workflows/test.yml
